In [1]:
# Learn Python
# default setting
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm
%matplotlib inline

In [11]:
# Working directory tools
import os
cwd = os.getcwd()
path=""
#os.chdir(path)
cwd

'C:\\Users\\zyx06\\OneDrive\\Documents\\Python\\3101'

In [ ]:
everything = []
for chunk in list_of_lists:
    everything.expend(chunk)

In [ ]:
# sort by specific keys
b=['saw', 'small', 'he', 'foxes', 'six']
b.sort(key = len)
b

In [9]:
import bisect
c=[1, 2, 2, 2, 3, 4, 7]
bisect.bisect(c, 2) # returns an insertion point which comes after (to the right of) any existing entries of item in list.

4

In [10]:
# enumerate
strings=['a', 'bc', 'def']
loc_mapping = {val:index for val, index in enumerate(strings)}
loc_mapping

{0: 'a', 1: 'bc', 2: 'def'}

In [22]:
# numpy array
data = np.random.randn(2, 3) # rand:uniform, randn:gaussian
arr = np.arange(10)
arr2 = arr[5:8].copy() # use slicing but not copy() will modify the original array as well
arr3 = np.zeros((3, 6))
arr4 = arr3.astype(np.int64) # .astype() always creates a new array
[arr3.ndim, arr3.shape, arr4.dtype]

[2, (3, 6), dtype('int64')]

In [34]:
# boolean indexing
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4).round(2)
data[~(names != 'Bob'), 2:] # ~ unselect the condition

cond = names == 'Bob'
data2=data[~cond]
data2[data2<0]=0
data2

array([[2.54, 1.08, 0.29, 0.47],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.07, 1.16, 0.  ],
       [1.16, 0.  , 0.  , 0.  ],
       [0.  , 2.18, 1.35, 0.28]])

In [23]:
# fancy indexing
arr = np.arange(32).reshape((8, 4))
arr.T # transpose
np.dot(arr.T, arr) # inner product
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [40]:
# unary functions
arr = np.random.randn(7) * 5
remainder, whole_part = np.modf(arr) # seperate fractional and integral parts
remainder

array([ 0.96405582,  0.25105172, -0.87753175,  0.3413452 ,  0.77092626,
        0.67517023,  0.18645624])

In [7]:
import sympy as sp
x = sp.symbols('x')
sp.expand((x-1)*(2*x+3)**2*(1-3*x))

-12*x**4 - 20*x**3 + 17*x**2 + 24*x - 9

In [3]:
def get_a(**values):
    return values['a']

#dct = {'a':1, 'b':2}
get_a(a=1, b=2)

1

In [6]:
# One line fibonacci
z = lambda x : x + 5
z(2)

fb = lambda x : fb(x-1) + fb(x-2) if x>2 else 1
[fb(i) for i in range(10)]

[1, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [2]:
# conditional logic in array
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr) # xarr, yarr can be scalars
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [6]:
# Boolean methods
arr = np.random.randn(100)
(arr > 0).sum() # number of positive values
[(arr > 0).any(), (arr > 0).all()]

[True, False]

In [7]:
# Unique sorting
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints) # sorted unique values -> sorted(set(ints))

array([1, 2, 3, 4])

In [ ]:
# Linear algebra
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1., 7.], [8., 9.]])
# x.dot(y)
np.dot(x, y) # matrix multiplication

# numpy linalg functions
X = np.random.randn(5, 5)
np.linalg.inv(X)
np.diag(X)
np.trace(X)
np.linalg.det(X) # determinant
np.linalg.eig(X) # eigenvalues and eigenvectors
np.linalg.qr(X)
np.linalg.svd(X)


In [23]:
# Random walks
nsteps = 1000
draws = np.random.randint(0, 2, size = nsteps) # random int form 0, 1
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()
(np.abs(walk) >= 10).argmax() # argmax returns first index of maximum value, giving us first time distance at 10

41

In [2]:
# pandas
import pandas as pd
#from pandas import Series, DataFrame

# Series
obj = pd.Series([4, 7, -5, 3])
obj = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])
pd.isnull(obj)
obj.name = 'sample'
obj.index.name = 'sample index'

In [12]:
# DataFrame
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year':[2000, 2001, 2002, 2001, 2002, 2003],
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
print(frame)

frame['state'] # retrieve column in DataFrame as Series
frame.state

frame.loc[1] # retrieve rows

frame['eastern'] = frame.state == 'Ohio' # add a boolean column
del frame['eastern'] # delete column

print(frame.columns)

frame.T # transpose

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2


Index(['state', 'year', 'pop'], dtype='object')

In [4]:
# Reindex
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill') # ffill fills forward, bfill fills backward
obj3

#frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
#print(frame)
#frame.loc[['a', 'b', 'c', 'd'], ['Texas', 'Utah', 'California']]

0      blue
2    purple
4    yellow
dtype: object

In [20]:
# Dropping entries
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')

frame.drop(['Texas', 'Ohio'], axis = 1) # drop columns in a DataFrame
obj.drop('c', inplace = True) # dropping in-place without returning a new object

In [23]:
# Indexing and Selection
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

data.loc['Colorado', ['two', 'three']] # selection with loc and iloc
data.iloc[2, [1, 2]]
data.loc[:, 'two'] # select single column

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [ ]:
# Arithmetic methods with fill values
df1 + df2 # any non overlap values become NAN(np.nan)
df1.add(df2, fill_value=0) # fill NAN(or none overlap) value with 0 and add together

In [9]:
# Function application
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
f = lambda x: x.max() - x.min()
frame.apply(f) # apply to each column, f can be a def function
frame.apply(f, axis = 'columns') # apply to each row

# Mapping
_format = lambda x: '%.2f' % x
frame.applymap(_format)

b      d      e
Utah    -0.35  -0.55  -1.34
Ohio     1.63   2.09   0.19
Texas   -0.11   0.01  -0.04
Oregon  -0.43   0.43  -0.19

In [12]:
# Sorting and Ranking
# sort by index
frame.sort_index()
frame.sort_index(axis=1) # sort according to columns
frame.sort_index(axis=1, ascending=False)

# sort by values
frame.sort_values(by='b')
frame.sort_values(by=['b', 'd']) # sort by multiple columns

# compute rank
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [14]:
# Descriptive statistics
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], 
                 index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
df.idxmax() # return maximum values index
df.cumsum()
df.describe()


one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [ ]:
# Correlation and Covariance
# returns is a DataFrame of stock returns
returns['AAPL'].corr(returns['MSFT']) # correlation of two columns in dataframe
returns['AAPL'].cov(returns['MSFT']) # covariance
returns.corr()

In [15]:
# Unique and counts
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64